### ISSUE TITLE
TypeError: rates.replaceAll is not a function

### ISSUE THREAD

**Issue by E-E-Ewoma-Zino** [paul-shuvo/nodejs-currency-converter#23] opened 2022-02-20 00:23 UTC
I am testing your package but I keep getting this error(TypeError: rates.replaceAll is not a function) when running the code from your docs

`const CC = require('currency-converter-lt')

let currencyConverter = new CC({from:"USD", to:"JPY", amount:100})

currencyConverter.convert().then((response) => {
    console.log(response) //or do something else
})`
What to do now??

![Screenshot 2022-02-20 012120](https://user-images.githubusercontent.com/69873736/154823609-a68d99bb-9254-4995-b550-75594cefe9a1.png)

**Comment by paul-shuvo** [comment] 2022-02-23 02:08
I think `replaceAll` was included in V8 8.5. Nodejs v15. I'll take a look into it. It should work for node version 15 and above.

**Comment by 2diegoduque** [comment] 2022-03-24 19:52
Hi, I still get this error.

**Comment by paul-shuvo** [comment] 2022-03-25 00:22
@2diegoduque what node version are you using?

**Comment by 2diegoduque** [comment] 2022-03-25 00:53
@paul-shuvo in my local 12.x environment, I updated it and it already worked, the problem is that I will use this code in an aws lambda that the maximum is 14.x

**Comment by paul-shuvo** [comment] 2022-03-25 06:01
I've pushed changes to the latest release `(1.3.0)`. Let me know if it works now; I'll close this issue.

**Closed as completed** 2022-03-25 19:13 UTC
Labels: bug

**Comment by 2diegoduque** [comment] 2022-03-27 15:49
> I've pushed changes to the latest release `(1.3.0)`. Let me know if it works now; I'll close this issue.

Until now I had the opportunity to try, and it worked perfectly, thanks
