### ISSUE TITLE
Rates Returns NaN

### ISSUE THREAD

**Issue by MohamedAmine-BenSalah** [paul-shuvo/nodejs-currency-converter#55] opened 2023-09-19 22:23 UTC
using this code : 
async function getRates() {
  let currencyConverter = new CC({ from: 'GBP', to: "EUR" });
  var rates = await currencyConverter.rates().catch(err=> console.log({err}));
  console.log("rates",rates)
}

getRates();

it works fine for my location but when i change to germany i get NaN.

**Comment by Muhammadmahadsaeed** [comment] 2023-10-05 17:48
@paul-shuvo

**Comment by paul-shuvo** [comment] 2023-10-06 15:48
Are you guys using the latest version?

**Comment by Muhammadmahadsaeed** [comment] 2023-10-06 17:10
Yes, i am using latest version and it was working fine before yesterday. I also checked it on Run kit. it is working fine on there.
Here is my code
const CurrencyConverter = require("currency-converter-lt");

let converter = new CurrencyConverter({ from: "RUB", to: "USD" });

module.exports.convertRubleToUSD = async (costInRuble) => {
    try {
        // Convert RUB to USD
        const convertedAmount = await converter.convert(costInRuble);
        return convertedAmount;
    } catch (error) {
        console.error('Error converting currency:', error.message);
        throw error;
    }
}

**Comment by paul-shuvo** [comment] 2023-10-06 17:55
Could you run the following and let me know what output you are getting?

```js
request(`https://www.google.com/search?q=Rub+to+USD&hl=en`, function(error, response, body) {
    if (error) {
      return reject(error);
    } else {
     console.log(body);
    }
  });
})
```

**Comment by Muhammadmahadsaeed** [comment] 2023-10-06 18:19
I downgraded it at v1.3.1 its working but I think its too slow. I also ruined that code but it showing me this error

node:internal/modules/cjs/loader:1000
    throw new ERR_INVALID_ARG_VALUE('id', id,
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at new NodeError (node:internal/errors:371:5)
    at Module.require (node:internal/modules/cjs/loader:1000:11)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Mahad\My Projects\easy-sms-backend\helper\helper.js:10:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_INVALID_ARG_VALUE'
}

**Comment by paul-shuvo** [comment] 2023-10-06 23:45
have you loaded the 'request' module?

```js
const request = require('request');
request(`https://www.google.com/search?q=Rub+to+USD&hl=en`, function(error, response, body) {
    if (error) {
      return reject(error);
    } else {
     console.log(body);
    }
});
```

**Comment by Muhammadmahadsaeed** [comment] 2023-10-07 13:42
yes, i am getting this error

node:internal/modules/cjs/loader:1000
throw new ERR_INVALID_ARG_VALUE('id', id,
^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
at new NodeError (node:internal/errors:371:5)
at Module.require (node:internal/modules/cjs/loader:1000:11)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. (C:\Mahad\My Projects\easy-sms-backend\helper\helper.js:10:21)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18) {
code: 'ERR_INVALID_ARG_VALUE'
}

**Comment by paul-shuvo** [comment] 2023-10-08 20:14
can you run it on runkit? It runs on runkit just fine

**Comment by Muhammadmahadsaeed** [comment] 2023-10-08 20:32
yes, I ran it on runkit. it works fine there and also it was working fine in my project but suddenly its was return Nan that's why I raised issue

**Comment by paul-shuvo** [comment] 2023-10-08 20:55
I meant the following piece of code:

```js
const request = require('request');
request(`https://www.google.com/search?q=Rub+to+USD&hl=en`, function(error, response, body) {
    if (error) {
      return reject(error);
    } else {
     console.log(body);
    }
});
```

**Comment by Muhammadmahadsaeed** [comment] 2023-10-08 20:57
no

**Comment by paul-shuvo** [comment] 2023-10-08 21:01
Could you run only the following piece of code on runkit and on your local machine and let me know what response you're getting?

```js
const request = require('request');
request(`https://www.google.com/search?q=Rub+to+USD&hl=en`, function(error, response, body) {
    if (error) {
      return reject(error);
    } else {
     console.log(body);
    }
});
```

**Comment by Muhammadmahadsaeed** [comment] 2023-10-08 21:25
runkit response
![image](https://github.com/paul-shuvo/nodejs-currency-converter/assets/46844969/3dbd8211-d975-4067-b243-30dd19cb8034)


my local machine response 
node:internal/modules/cjs/loader:1000
throw new ERR_INVALID_ARG_VALUE('id', id,
^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
at new NodeError (node:internal/errors:371:5)
at Module.require (node:internal/modules/cjs/loader:1000:11)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. (C:\Mahad\My Projects\easy-sms-backend\helper\helper.js:10:21)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18) {
code: 'ERR_INVALID_ARG_VALUE'
}

**Comment by paul-shuvo** [comment] 2023-10-08 21:41
Could you use [got](https://www.npmjs.com/package/got) instead of `request` and see if you're able to get any response on your system

**Comment by Muhammadmahadsaeed** [comment] 2023-10-08 21:46
no

**Comment by paul-shuvo** [comment] 2023-10-08 21:53
Could you try any other url other than `google`'s and let me know if you getting any response?

**Comment by Muhammadmahadsaeed** [comment] 2023-10-09 15:04
Sure, I will do it for you but I am not sure what is the issue behind this because it was working fine before raising issue

**Comment by paul-shuvo** [comment] 2023-10-09 15:12
The issue, I suspect, is that you're making too many requests and Google probably has flagged your IP. The problem is not with parsing rather you're not getting any response from HTTP requests.

**Comment by Muhammadmahadsaeed** [comment] 2023-10-11 13:00
yeah i am making too many request because i want to convert list of prices

**Comment by paul-shuvo** [comment] 2023-10-11 16:17
I see; a solution could be to cache the conversions and use a longer time resolution. As this is something out of the scope of this project, I'm closing this issue.

**Closed as completed by paul-shuvo** 2023-10-11 16:17 UTC
